### DISCUSSION TITLE
支持ipv6解析的抗污染么？

### DISCUSSION THREAD

**Discussion by echowings** [LEXUGE/dcompass#84] [Q&A] [answered]
Hi Admin
请问如何支持ipv6地址解析抗污染么？

**Comment by LEXUGE** [comment]
支持的。
抗污染有两种办法：根据请求的域名分流，以及根据返回的IP分流。
前者不受IP或请求类型影响，后者则只需要IP数据库支持IPv6即可。

**Reply by echowings** [reply]
请问有计划支持ipv6抗污染功能么？

**Reply by LEXUGE** [reply]
按照上面的回复，目前是支持的

**Comment by echowings** [comment]
如何调整参数呢？

**Comment by LEXUGE** [comment, marked as answer]
如果你使用了 geoip 插件，那并不需要调整任何参数。

如果你使用了IP CIDR来过滤，只需要确保你的IP CIDR列表规则里包含了需要过滤的IPv6地址即可，

**Comment by echowings** [comment]
谢谢，我试试

**Comment by echowings** [comment]
it works! thanks!
```yaml
---
verbosity: "info"
address: 0.0.0.0:53
table:
  start:
    - dispatch
  dispatch:
    - query: domestic
    - check_secure
  check_secure:
    if: |
      geoip(codes: ["CN"])
    else:
      - query: secure
      - end

upstreams:
  114DNS:
    udp:
      addr: 114.114.114.114:53

  Ali:
    udp:
      addr: 223.6.6.6:53

  domestic:
    hybrid:
      - 114DNS
      - Ali

  cloudflare1:
    udp:
      addr: 1.0.0.1:53

  cloudflare2:
    udp:
      addr: 1.1.1.1:53
  quad9:
    udp:
      addr: 9.9.9.9:53
  googledns1:
    udp:
      addr: 8.8.8.8:53
  googledns2:
    udp:
      addr: 8.8.4.4:53



  secure:
    hybrid:
      - googledns1
      - googledns2
      - cloudflare1
      - cloudflare2
      - quad9
```
