### ISSUE TITLE
[BUG] 无法设置基于ipv6的dns上游

### ISSUE THREAD

**Issue by PussAzuki** [LEXUGE/dcompass#43]
**Describe the bug 发生了什么**
如题

**To Reproduce 如何重现**
其他保持不变，然后在上游部分添加像下面这样设置 然后用 ./dcompass -c ./config.yaml -v 测试时会发现报错

```
  - method:
      https:
        no_sni: true
        name: cloudflare-dns.com
        addr: '[2606:4700:4700::1111]'
    tag: Cloudflare_B
```
`2606:4700:4700::1111`和`'[2606:4700:4700::1111]'`都是报错 `method.https.addr: invalid IP address syntax`
`[2606:4700:4700::1111]` 报错 `method.https.addr: invalid type: sequence, expected socket address`

**Version & Platform (please complete the following information) 版本信息**
 - Variant: dcompass-x86_64-pc-windows-gnu-min.exe
- OS: Windows 10
 - Version build-20210311_0946

**Comment by LEXUGE** [comment]
这个 Addr 应该是 `[2001:db8::1]:8080` 这样的形式，也就是说是要有端口号的
这里的端口号应该是 443

**Comment by PussAzuki** [comment]
当使用 `[2606:4700:4700::1001]:443` 时，会出现 `while parsing a block mapping, did not find expected key` 错误

**Comment by LEXUGE** [comment]
请提供一下完整配置和 `debug` level 的 log

**Comment by PussAzuki** [comment]
```
---
verbosity: 'info'
cache_size: 4096
address: 0.0.0.0:2053
table:
  - tag: all_work
    if:
      qtype:
        - A
        - AAAA
    then:
      - match_remote_domain
    else:
      - disable
      - end
  - tag: match_remote_domain
    if:
      domain:
        - google.com
        - youtube.com
    then:
      - query: remote_dns
      - end
  - tag: match_local_domain
    if:
      domain:
        - bilibili.com
        - baidu.com
    then:
      - query: local_dns
      - end
  - tag: match_a_query
    if:
      qtype:
        - A
    then:
      - query: local_dns
      - match_cn_ip
  - tag: match_aaaa_query
    if:
      qtype:
        - AAAA
    then:
      - query: remote_dns
      - end
  - tag: match_cn_ip
    if:
      ipcidr:
        - 192.168.7.1
    else:
      - query: remote_dns
      - end

upstreams:
  - method:
      https:
        no_sni: true
        name: dns.alidns.com
        addr: 223.6.6.6:443
    tag: Alidns_A
  - method:
      https:
        no_sni: true
        name: dns.alidns.com
        addr: 223.5.5.5:443
    tag: Alidns_B
  - method:
      https:
        no_sni: true
        name: doh.pub
        addr: 162.14.21.178:443
    tag: DNSPod_A
  - method:
      https:
        no_sni: true
        name: doh.pub
        addr: 162.14.21.56:443
    tag: DNSPod_B
  - method:
      hybrid:
      - Alidns_A
      - Alidns_B
      - DNSPod_A
      - DNSPod_B
    tag: local_dns
  - method:
      https:
        no_sni: true
        name: cloudflare-dns.com
        addr: [2606:4700:4700::1001]:443
    tag: Cloudflare_A
  - method:
      https:
        no_sni: true
        name: cloudflare-dns.com
        addr: '[2606:4700:4700::1111]'
    tag: Cloudflare_B
  - method:
      https:
        no_sni: true
        name: dns.google
        addr: '[2001:4860:4860::8844]'
    tag: Google_A
  - method:
      https:
        no_sni: true
        name: dns.google
        addr: '[2001:4860:4860::8888]'
    tag: Google_B
  - method:
      hybrid:
      - Cloudflare_A
      - Cloudflare_B
      - Google_A
      - Google_B
    tag: remote_dns
```

因为是测试用 所以就随便填了域名
然后我发现 then 后面只能接一个动作之后就得下个if了(测试的时候才发现有这个限制，但是决定先全测试完了) 像mosdns那样能无限if套娃不好吗(节省写多个tag的空间)
目前期望是接受A和AAAA的结果然后国内AAAA的结果还要被过滤掉

**Comment by LEXUGE** [comment]
then 和 else 后是支持多个action的
以及domain后面不应该写域名，而应该是存放域名列表的文件名称
尝试把addr用双引号包裹一下，解析文件错误也是有行号的，可以根据这个来debug

不支持if嵌套的原因是避免语法复杂化。
dcompass是确保routine是deterministic和fully exposed的，也就是说保证routine结果的一致性，且”可停机”。并且还会检查upstreams的availability。如果支持if嵌套会复杂化这个check的算法。后期会支持expression engine来处理and or这类的逻辑，优化体验。不过我还是坚持正确性大于功能性。

**Comment by PussAzuki** [comment]
```
    then:
      - match_remote_domain
      - match_local_domain
      - end
```

当如上设置时，会出现 `Extra element after the rule tag specified at last` 错误(这个错误老是出来)
domain那里我随便写的 也不知您这里支不支持读v2ray那种dat文件
addr 那里 `"[2606:4700:4700::1001]:443" ` 看起来能行

然后认为能跑之后出了如下的错误
```
Error: An I/O error encountered. Check files provided for matcher(s) to ensure they exist and have the right permissions.

Caused by:
    系统找不到指定的文件。 (os error 2
)

**Comment by LEXUGE** [comment]
`match_remote_domain` 这类的是 tag name，action 是 `disable`, `query` 这类的，请看 README
每个 branch 的语义是：
1. action1
2. action2
3. action3
...
4. 下一步跳转的 tag

未来可能会支持 tag name 和 action 混合，来实现类似函数跳转的控制流
并不支持 dat 文件，支持 https://github.com/felixonmars/dnsmasq-china-list

**Comment by LEXUGE** [comment]
> 目前期望是接受A和AAAA的结果然后国内AAAA的结果还要被过滤掉

一个可能的配置：
自动根据 GeoIP 分流，如果是国内且 qtype 为 AAAA，那么就丢弃结果
```
---
verbosity: 'info'
cache_size: 4096
address: 0.0.0.0:2053
table:
- tag: start
  if: any
  then:
  - query: domestic
  - check_secure
- tag: check_secure
  if:
    geoip:
      codes:
        - CN
  then:
  - check_aaaa
  else:
  - query: secure
  - end
- tag: check_aaaa
  if:
    qtype:
      - AAAA
  then:
  - disable
  - end

upstreams:
- method:
    udp:
      addr: 114.114.114.114:53
  tag: 114DNS

- method:
    https:
      addr: 9.9.9.9:443
      no_sni: true
      name: dns.quad9.net
  tag: secure

- method:
    udp:
      addr: 223.6.6.6:53
  tag: Ali

- method:
    hybrid:
    - 114DNS
    - Ali
  tag: domestic
```
