### ISSUE TITLE
Better documentation needed on Unknown variant for the query matcher.

### ISSUE THREAD

**Issue by bcookatpcsd** [LEXUGE/dcompass#46]
Not sure what I am doing wrong.. 

 /opt/bin/dcompass -v -c /etc/dcompass/tls.yaml-wip 
Using the config file specified: /etc/dcompass/tls.yaml-wip
Error: Failed to parse the configuration file

Caused by:
    table[0]: data did not match any variant of untagged enum ParMatcher at line 6 column 6

  1 ---
  2 verbosity: 'error'
  3 cache_size: 4096
  4 address: 0.0.0.0:2053
  5 table:
  6 - tag: start
  7   if:
  8     qtype:
  9       - A
 10       - ANY
 11       - DNSKEY
 12       - DS
 13       - HINFO
 14       - MX
 15       - NS
 16       - SRV
 17       - TXT
 18   then:
 19   - dispatch
 20   else:
 21   - blackhole
 22   - end
 23 
 24 - tag: dispatch
 25   if: any
 26   then:
 27   - query: secure
 28   - end
 29 

yaml formatting issue? or syntax error? or possible Unknown dns types 

https://en.wikipedia.org/wiki/List_of_DNS_record_types

- Thanks in advance..

**Comment by LEXUGE** [comment]
Yes, I think it should be a format issue, cause YAML is very strict on space or something like that. Would you like to use
Markdown code block to repost your config here?

**Comment by bcookatpcsd** [comment]
https://pastebin.com/78P7kGb9

/opt/bin/dcompass -v -c /etc/dcompass/tls-wip.yaml
Using the config file specified: /etc/dcompass/tls-wip.yaml
Error: Failed to parse the configuration file

Caused by:
    table[0]: data did not match any variant of untagged enum ParMatcher at line 6 column 6

What is wrong?

**Comment by bcookatpcsd** [comment]
/opt/bin/dcompass -c /etc/dcompass/tls-wip.json -v
Using the config file specified: /etc/dcompass/tls-wip.json
Error: Failed to parse the configuration file

Caused by:
    table[0]: data did not match any variant of untagged enum ParMatcher at line 6 column 7

https://www.convertjson.com/yaml-to-json.htm

```
{
   "verbosity": "error",
   "cache_size": 4096,
   "address": "0.0.0.0:2054",
   "table": [
      {
         "tag": "start",
         "if": {
            "qtype": [
               "A",
               "ANY",
               "DNSKEY",
               "DS",
               "HINFO",
               "MX",
               "NS",
               "SRV",
               "TXT"
            ]
         },
         "then": [
            "dispatch"
         ],
         "else": [
            "blackhole",
            "end"
         ]
      },
      {
         "tag": "dispatch",
         "if": "any",
         "then": [
            {
               "query": "secure"
            },
            "end"
         ]
      }
   ],
   "upstreams": [
      {
         "method": null,
         "tls": {
            "no_sni": false,
            "name": "dns.nextdns.io",
            "addr": "45.90.28.0:853",
            "tag": "nextdns-28"
         }
      },
      {
         "method": null,
         "tls": {
            "no_sni": false,
            "name": "dns.nextdns.io",
            "addr": "45.90.30.0:853",
            "tag": "nextdns-30"
         }
      },
      {
         "method": null,
         "hybrid": [
            "nextdns-28",
            "nextdns-30"
         ],
         "tag": "secure"
      }
   ]
} 
```

**Comment by LEXUGE** [comment]
https://docs.rs/trust-dns-proto/0.20.1/trust_dns_proto/rr/record_type/enum.RecordType.html

Currently, the query type matcher can only support those in the above link. Other types have to be matched using `Unknown: ...`

You can use the wikipedia page you posted to find out the number for your query type.

**Comment by bcookatpcsd** [comment]
_THANK YOU_

The Mrs wanted to kill be b/c I keep talking about this.. 

I never thought to look whats supported in rust.. I just thought 64 and 65 were "new", and that's why.. 

Will post working config with new data after reading.. 

btw, anyway to work on the error message? 

I thought it was a formatting issue.. I never would have ended up at "unsupported" query type.. 

My 0.02

**Comment by LEXUGE** [comment]
Well, the config parser can only tell that it doesn’t match any of the known type, so it errored. But it could be better I think.

**Comment by LEXUGE** [comment]
You can also subscribe to the following telegram channel https://t.me/dcompass_channel to have up to date information regarding breaking changes I made, because sometimes I may not be able to change the README.

**Comment by bcookatpcsd** [comment]
```
---
verbosity: 'info'
cache_size: 4096
address: 0.0.0.0:2053

table:
- tag: start 
  if:
    qtype:
      - A
      - ANY
      - CNAME
      - MX
      - NS
      - PTR
      - SOA
      - TXT
      - Unknown: 48
      - Unknown: 43
      - Unknown: 13
  then:
      - dispatch
  else:
      - blackhole
      - end

- tag: dispatch
  if: any
  then:
      - query: secure
      - end
```

rust docs say hinfo is supported, but I had to use Unknown: 13 to get it working.. 
_dunno_

Looks great, and is working.. 

```
upstreams:
- method:
    tls:
      no_sni: false
      name: dns.nextdns.io
      addr: 45.90.28.0:853
  tag: nextdns-28

- method:
    tls:
      no_sni: false
      name: dns.nextdns.io
      addr: 45.90.30.0:853
  tag: nextdns-30

- method:
    hybrid:
      - nextdns-28
      - nextdns-30
  tag: secure
```

the tag, needed to be outdented aligned with method..

That was the only odd thing.

But it's working.. 

```
● dcompass.service - dcompass systemd service.
     Loaded: loaded (/etc/systemd/system/dcompass.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-03-16 21:43:04 EDT; 4min 19s ago
   Main PID: 1016673 (dcompass)
      Tasks: 9 (limit: 9396)
     Memory: 6.5M
        CPU: 586ms
     CGroup: /system.slice/dcompass.service
             └─1016673 /opt/bin/dcompass -c /etc/dcompass/tls-wip.yaml

```

Thank you for all your help..
